Fixed `AttributeError`: module 'pytest_cases' has no attribute 'CasesCollectionWarning' when running `pytest-xdist` and at least one cases class is ignored because of `__init__` or `__new__`. Fixed #249 (#267)
Co-authored-by: Sylvain MARIE <sylvain.marie@se.com>