- Fixed `AttributeError: 'MiniMetafunc' object has no attribute '_params_directness'` when a case function is   parametrized or requires a fixtures, with pytest 8.4.0. Fixed #365 - Fixed `ValueError: The provided fixture function does not seem to be a fixture` with `@fixture_ref`  with pytest   8.4.0. Fixed #364