Fixed compat with pytest 8.4.0 (#367)
* - Fixed `AttributeError: 'MiniMetafunc' object has no attribute '_params_directness'` when a case function is
  parametrized or requires a fixtures, with pytest 8.4.0. Fixed #365
- Fixed `ValueError: The provided fixture function does not seem to be a fixture` with `@fixture_ref`  with pytest
  8.4.0. Fixed #364

* Updated license

* Removed useless code in nox file

* Removed useless requirement for packaging as setup dependency, and added a few comments/docstring

* Added additional combinations in the cicd matrix

* Enabled support for python 3.14

---------

Co-authored-by: Sylvain MARIE <sylvain.marie@se.com>